### PR TITLE
Update experience.asm

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by JustRegularLuna** [comment]
I'm not interested in disabling stat exp gain in this base.

**Comment by ghost** [comment]
I wanted to do this in the fork and not in your repository, but I just started using github. Any help is welcome!

**Comment by JustRegularLuna** [comment]
What were you actually wanting to do? Pull the changes from my repo over into yours, instead of the other way around?

**Comment by ghost** [comment]
I wanted to have a repository same as yours, so that I can apply changes you make in the source while make my own changes. I also wondered if you can help me with some clarifications about hacking. I am learning right now and while I have done some things I have come across some problems. If we could communicate through email I would like to ask you some questions, if you are willing to help/teach me. Thank you!!

**Pull request closed without merging**
